import Head from 'next/head'

export default function AppHead({
  title,
  favicon,
}: {
  title?: string
  favicon?: string
}) {
  return (
    <Head>
      <title>{title || 'ChatsApp'}</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href={favicon || '/images/favicon.ico'} />
    </Head>
  )
}
